[package]
name = "pingkikai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dark-light = "1.0.0"
iced = "0.10.0"
reqwest = { version = "0.11.23", features = ["blocking"] }
